//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.31 at 02:24:35 PM CST 
//


package com.my.project.winscp.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://winscp.net/schema/session/1.0}command"/>
 *         &lt;element ref="{http://winscp.net/schema/session/1.0}destination"/>
 *         &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *           &lt;choice>
 *             &lt;element ref="{http://winscp.net/schema/session/1.0}output"/>
 *             &lt;element ref="{http://winscp.net/schema/session/1.0}erroroutput"/>
 *           &lt;/choice>
 *         &lt;/sequence>
 *         &lt;element ref="{http://winscp.net/schema/session/1.0}result"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "command",
    "destination",
    "outputOrErroroutput",
    "result"
})
@XmlRootElement(name = "call")
public class Call {

    @XmlElement(required = true)
    protected StringValueType command;
    @XmlElement(required = true)
    protected StringValueType destination;
    @XmlElementRefs({
        @XmlElementRef(name = "output", namespace = "http://winscp.net/schema/session/1.0", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "erroroutput", namespace = "http://winscp.net/schema/session/1.0", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<StringValueType>> outputOrErroroutput;
    @XmlElement(required = true)
    protected Result result;

    /**
     * Gets the value of the command property.
     * 
     * @return
     *     possible object is
     *     {@link StringValueType }
     *     
     */
    public StringValueType getCommand() {
        return command;
    }

    /**
     * Sets the value of the command property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValueType }
     *     
     */
    public void setCommand(StringValueType value) {
        this.command = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link StringValueType }
     *     
     */
    public StringValueType getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValueType }
     *     
     */
    public void setDestination(StringValueType value) {
        this.destination = value;
    }

    /**
     * Gets the value of the outputOrErroroutput property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outputOrErroroutput property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutputOrErroroutput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link StringValueType }{@code >}
     * {@link JAXBElement }{@code <}{@link StringValueType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<StringValueType>> getOutputOrErroroutput() {
        if (outputOrErroroutput == null) {
            outputOrErroroutput = new ArrayList<JAXBElement<StringValueType>>();
        }
        return this.outputOrErroroutput;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link Result }
     *     
     */
    public Result getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link Result }
     *     
     */
    public void setResult(Result value) {
        this.result = value;
    }

}
