//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.31 at 02:24:35 PM CST 
//


package com.my.project.winscp.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://winscp.net/schema/session/1.0}filename" minOccurs="0"/>
 *         &lt;element ref="{http://winscp.net/schema/session/1.0}type"/>
 *         &lt;element ref="{http://winscp.net/schema/session/1.0}size" minOccurs="0"/>
 *         &lt;element ref="{http://winscp.net/schema/session/1.0}modification"/>
 *         &lt;element ref="{http://winscp.net/schema/session/1.0}permissions"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "filename",
    "type",
    "size",
    "modification",
    "permissions"
})
@XmlRootElement(name = "file")
public class File {

    protected StringValueType filename;
    @XmlElement(required = true)
    protected FileTypeValueType type;
    protected SizeValueType size;
    @XmlElement(required = true)
    protected DateTimeValueType modification;
    @XmlElement(required = true)
    protected StringValueType permissions;

    /**
     * Gets the value of the filename property.
     * 
     * @return
     *     possible object is
     *     {@link StringValueType }
     *     
     */
    public StringValueType getFilename() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValueType }
     *     
     */
    public void setFilename(StringValueType value) {
        this.filename = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link FileTypeValueType }
     *     
     */
    public FileTypeValueType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileTypeValueType }
     *     
     */
    public void setType(FileTypeValueType value) {
        this.type = value;
    }

    /**
     * Gets the value of the size property.
     * 
     * @return
     *     possible object is
     *     {@link SizeValueType }
     *     
     */
    public SizeValueType getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     * 
     * @param value
     *     allowed object is
     *     {@link SizeValueType }
     *     
     */
    public void setSize(SizeValueType value) {
        this.size = value;
    }

    /**
     * Gets the value of the modification property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeValueType }
     *     
     */
    public DateTimeValueType getModification() {
        return modification;
    }

    /**
     * Sets the value of the modification property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeValueType }
     *     
     */
    public void setModification(DateTimeValueType value) {
        this.modification = value;
    }

    /**
     * Gets the value of the permissions property.
     * 
     * @return
     *     possible object is
     *     {@link StringValueType }
     *     
     */
    public StringValueType getPermissions() {
        return permissions;
    }

    /**
     * Sets the value of the permissions property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValueType }
     *     
     */
    public void setPermissions(StringValueType value) {
        this.permissions = value;
    }

}
