//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.31 at 02:24:35 PM CST 
//


package com.my.project.winscp.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;choice>
 *           &lt;element ref="{http://winscp.net/schema/session/1.0}failure"/>
 *           &lt;element ref="{http://winscp.net/schema/session/1.0}upload"/>
 *           &lt;element ref="{http://winscp.net/schema/session/1.0}download"/>
 *           &lt;element ref="{http://winscp.net/schema/session/1.0}touch"/>
 *           &lt;element ref="{http://winscp.net/schema/session/1.0}chmod"/>
 *           &lt;element ref="{http://winscp.net/schema/session/1.0}mkdir"/>
 *           &lt;element ref="{http://winscp.net/schema/session/1.0}rm"/>
 *           &lt;element ref="{http://winscp.net/schema/session/1.0}mv"/>
 *           &lt;element ref="{http://winscp.net/schema/session/1.0}call"/>
 *           &lt;element ref="{http://winscp.net/schema/session/1.0}ls"/>
 *           &lt;element ref="{http://winscp.net/schema/session/1.0}stat"/>
 *           &lt;element ref="{http://winscp.net/schema/session/1.0}cp"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="start" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "failureOrUploadOrDownload"
})
@XmlRootElement(name = "group")
public class Group {

    @XmlElements({
        @XmlElement(name = "failure", type = Failure.class),
        @XmlElement(name = "upload", type = Upload.class),
        @XmlElement(name = "download", type = Download.class),
        @XmlElement(name = "touch", type = Touch.class),
        @XmlElement(name = "chmod", type = Chmod.class),
        @XmlElement(name = "mkdir", type = Mkdir.class),
        @XmlElement(name = "rm", type = Rm.class),
        @XmlElement(name = "mv", type = Mv.class),
        @XmlElement(name = "call", type = Call.class),
        @XmlElement(name = "ls", type = Ls.class),
        @XmlElement(name = "stat", type = Stat.class),
        @XmlElement(name = "cp", type = Cp.class)
    })
    protected List<Object> failureOrUploadOrDownload;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "start", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar start;

    /**
     * Gets the value of the failureOrUploadOrDownload property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the failureOrUploadOrDownload property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFailureOrUploadOrDownload().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Failure }
     * {@link Upload }
     * {@link Download }
     * {@link Touch }
     * {@link Chmod }
     * {@link Mkdir }
     * {@link Rm }
     * {@link Mv }
     * {@link Call }
     * {@link Ls }
     * {@link Stat }
     * {@link Cp }
     * 
     * 
     */
    public List<Object> getFailureOrUploadOrDownload() {
        if (failureOrUploadOrDownload == null) {
            failureOrUploadOrDownload = new ArrayList<Object>();
        }
        return this.failureOrUploadOrDownload;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStart(XMLGregorianCalendar value) {
        this.start = value;
    }

}
